### ISSUE TITLE
Failed to minify Auth.js when building with react

### ISSUE THREAD

**Issue by ivoilic** [okta/okta-oidc-js#49]
When attempting to create a production build with react it fails and I get this error:
> Failed to minify the code from this file: 
>
>	./node_modules/@okta/okta-react/dist/Auth.js:54 

It's suggested [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) that the package be published pre-compiled.

**Comment by lboyette-okta** [comment]
Thank for filing an issue! It's now resolved in master.

**Comment by sateesh2020** [comment]
@lboyette-okta 
Can you please update this in the npm please, It still have the old version.
