### ISSUE TITLE
AuthSdkError: The redirectUri passed to /authorize must also be passed to /token

### ISSUE THREAD

**Issue by sleepwalky** [okta/okta-oidc-js#775]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

From time to time we're receiving the following error:
![image](https://user-images.githubusercontent.com/14991709/81927052-abc6b100-95eb-11ea-9df2-e8aa88066d47.png)
Usually it happens when the app wasn't used for some time (maybe 10 hours or next day morning). User accesses the app, then being redirected to okta login form, successfully logins and then redirected to /implicit/callback url and then this error appears.

Is there anything we can do to stop getting this error?

## Minimal reproduction of the problem with instructions

We couldn't find the way to reproduce in with 100% success rate, it's just happens occasionally.

## Environment

- Package Version: 3.0.1
- Browser: Chrome
- OS: MacOS
- Node version (`node -v`):
- Other:

**Comment by swiftone** [comment]
@sleepwalky - Thanks for the report.  We are tracking some issues involving stale sessions, but the exact error message you are reporting is not quite the same.  

Are you using just the okta-react SDK or also the sign-in-widget?  If you are using the widget, what sort of post-login logic are you using?

For clarity, you're saying that the order of events is:

- user is logged in, app is working
- app is left sitting
- user returns, app shows...what?
- user attempts to logins
- on redirect back to /implicit/callback, this is when the error appears?

**Comment by swiftone** [comment]
Likely related to https://github.com/okta/okta-auth-js/issues/381

**Comment by KozhemyakinLyft** [comment]
Hi, @swiftone 
Some details about issue above:

1. User has been logged
2. User was waiting in offline (access token is expired and didn't refresh)
3. User clicked any link in the App (our links are SecureRoutes)
4. User redirected to login screen
5. User relogined again
6. /implicit/callback error appears

Note: after clicking on the same link again - everything is good

**Comment by swiftone** [comment]
@sleepwalky @KozhemyakinLyft - 

We located an issue where the underlying okta-auth-js library could kick off overlapping PKCE renewal requests that don't play well with one another.  Could you update your installs to ensure you have the latest (3.1.2+) version of that (it is a dependency of okta-react/okta-angular/okta-vue, so those SDK versions have not yet themselves updated) and see if it helps with the symptoms?

That's not the only potential cause we're looking at, so your feedback can help narrow down what is causing this issue for you.  

Thanks in advance!

**Comment by sleepwalky** [comment]
thanks @swiftone !

next week we'll deploy the app with updated @okta/okta-auth-js on staging and we'll let you know if it resolves the issue

**Comment by aarongranick-okta** [comment]
@sleepwalky @KozhemyakinLyft We have released a new version of okta-auth-js (3.1.3) which may help resolve this issue. If you run yarn or npm install, it should automatically install the latest version of `okta-auth-js` as a dependency of okta-react.

**Comment by sleepwalky** [comment]
Unfortunately, we noticed that after updating to 3.1.2 the issue still appeared, so we're eager to try 3.1.3 😄 
Thank you for letting us know, @aarongranick-okta!

**Comment by sleepwalky** [comment]
@swiftone @aarongranick-okta 
We don't see this particular issue anymore, so I assume updating to 3.1.3 helped

**Comment by sandunes** [comment]
I'm on` okta-auth-js 3.2.1 (okta-react 3.0.3)` and I'm seeing this issue in both Chrome and Firefox(in both private and regular tabs).

**Comment by dimotech** [comment]
I'm on okta-auth-js 3.2.1 and okta-react 1.4.1, I am seeing this error in safari and it will keep refreshing the page constantly. And some time in chrome, it will show AuthSdkError: unable to retrieve OAuth redirect params cookie. Anyone can give some helps here? Really appreciate it!

**Comment by swiftone** [comment]
@dimotech - Are you using okta-react AND the signin-widget?   If so, make sure your okta-react is using the latest okta-auth-js (3.2.2+) as we added a change to resolve conflicts between the okta-auth-js bundled with the widget and any okta-auth-js used outside of the widget (such as in okta-react).

Let us know if that clears up the issue.  Otherwise, I'd look into upgrading your okta-react to the latest, as it has quite a few changes in okta-react 3.x.  You can see the steps necessary to migrate to the newer version here: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#migrating-from-1x-to-20
